### PR TITLE
[WIP] Cgmes fix regulating terminal

### PR DESCRIPTION
**Pull request by marqueslanauja**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the current behavior?** *(You can also link to an open issue here)*
In some models there are `phaseTapChangers` controlling flow where the `regulatingTerminal` is associated with a `busBarSection` terminal.

**What is the new behavior (if this is a feature change)?**
The `regulatingTerminal`  has been moved to the `transformerEnd` terminal if both are at the same `connectivityNode` (They are connected only by `internalConnections`)

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

**Review by MioRtia — COMMENTED** [review]
The solution is okay for me but shouldn't this fix be also done for reactive power regulation of generators?

**Review by MioRtia — CHANGES_REQUESTED** [review]
Second comment: maybe it is better (less confusing) to modify the method `findRegulatingTerminal` and filter bbs terminals if it is a flow regulation

**Comment by zamarrenolm** [comment]
> Second comment: maybe it is better (less confusing) to modify the method `findRegulatingTerminal` and filter bbs terminals if it is a flow regulation

I would keep `findRegulatingTerminal` as it is.

The `findRegulatingTerminal` works ok here: the regulating terminal specified in the regulating control has been mapped to IIDM and is connected, so it is found directly.

The problem is that the original CGMES definition of the regulating terminal was incorrect. We are trying to fix a problem in the original data, not trying to recover an equivalent terminal that has been lost during the mapping from CGMES to IIDM.

**Comment by zamarrenolm** [comment]
> The solution is okay for me but shouldn't this fix be also done for reactive power regulation of generators?

You are totally right, a similar reasoning applies to this kind of regulation. We have not found any real world case yet, but we could apply a similar fix for that situation.

**Comment by annetill** [comment]
@zamarrenolm  Can we close this PR?

**Comment by zamarrenolm** [comment]
> @zamarrenolm Can we close this PR?

I think so. We will analyze this after the changes we have made in #2042. If the case described here does not work after the changes in #2042 we will re-implement the solution using the new `RegulatingTerminalMapper` class.

**Pull request closed without merging**
