### PR TITLE
CGMES: add support for Equivalent Branches at boundaries

### PR DESCRIPTION
**Pull request by zamarrenolm**
Signed-off-by: Luma <zamarrenolm@aia.es>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the current behavior?** *(You can also link to an open issue here)*
Supported objects at boundaries are only ACLineSegment and Switches. 

**What is the new behavior (if this is a feature change)?**
Allow Equivalent Branches with one end at boundary. They will be mapped to an IIDM dangling line if an individual grid model is being loaded.

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:
Observed in some real-world models.

### CODE REVIEW

**Review by MioRtia — COMMENTED** [review]
I agree that it works for EquivalentBranch at Boundary, but does it work when we import a CGM with EquivalentBranch-ACLineSegment junction? It seems that for that, the `delayedNodes` list should be used... Or will we handle this in a later PR? What do you think @annetill?

**Comment by zamarrenolm** [comment]
> I agree that it works for EquivalentBranch at Boundary, but does it work when we import a CGM with EquivalentBranch-ACLineSegment junction? It seems that for that, the `delayedNodes` list should be used... Or will we handle this in a later PR? What do you think @annetill?

It will work if we create a CGM from multiple IGMs imported separately. Each IGM will create their dangling lines and the `MergingView` or the destructive merge will combine them in a `MergedLine` / `TieLine`.

The only scenario where this solution is not complete is when we import multiple EQ files (from many IGMs) in a single conversion (to build a single Network). As an example: the "Assembled" MicroGrid files of the ENTSO-E conformity tests, where BE and NL files are imported together. We will cover this configuration in the next PR about transformers at boundaries, where we have refactored a little bit how the different combinations of equipment at a boundary are handled for assembled imports.

**Review by marqueslanauja — APPROVED** [review]

**Comment by zamarrenolm** [comment]
Handling of equipment that can be found at boundaries will be completed in #1682, for IGM, CGM and assembled conversions.

**Comment by MioRtia** [comment]
> > I agree that it works for EquivalentBranch at Boundary, but does it work when we import a CGM with EquivalentBranch-ACLineSegment junction? It seems that for that, the `delayedNodes` list should be used... Or will we handle this in a later PR? What do you think @annetill?
> 
> It will work if we create a CGM from multiple IGMs imported separately. Each IGM will create their dangling lines and the `MergingView` or the destructive merge will combine them in a `MergedLine` / `TieLine`.
> 
> The only scenario where this solution is not complete is when we import multiple EQ files (from many IGMs) in a single conversion (to build a single Network). As an example: the "Assembled" MicroGrid files of the ENTSO-E conformity tests, where BE and NL files are imported together. We will cover this configuration in the next PR about transformers at boundaries, where we have refactored a little bit how the different combinations of equipment at a boundary are handled for assembled imports.

Okay, thank you for your answer! I agree with that and this PR is okay for me otherwise.

**Review by MioRtia — APPROVED** [review]

**Pull request merged**
