### PR TITLE
Export tculControlMode as volt by default in CGMES 2.4.15 and prevent export of the attribute in 3.0

### LINKED ISSUE #2928: CGMES export tculControlMode as volt by default
### Describe the current behavior

`tculControlMode` is exported as `reactive` when RTC regulation is enabled and as `volt` when regulation is disabled.

### Describe the expected behavior

In most of the cases RTC regulates voltage so `volt` should be exported by default.

### Describe the steps

_No response_

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by nemanja-st**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
Fixes #2928 

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by annetill** [comment]
> @annetill This attribute was first implemented in #2328
> 
> In CGMES 3.0 the attribute doesn't exist and in 2.4.15 it doesn't have meaning while it's mandatory.
> 
> Proposal is to keep it as `volt` now in order not to change it when regulation is enabled/disabled on RTC.

Do we manage with your PR to not export this attribute in 3.0?

**Comment by nemanja-st** [comment]
> > @annetill This attribute was first implemented in #2328
> > In CGMES 3.0 the attribute doesn't exist and in 2.4.15 it doesn't have meaning while it's mandatory.
> > Proposal is to keep it as `volt` now in order not to change it when regulation is enabled/disabled on RTC.
> 
> Do we manage with your PR to not export this attribute in 3.0?

No, I’m not sure if this method is shared between 2.4.15 and 3.0.

I think export of the attributes should be handled in the cgmes 3.0 export of RatioTapChanger.

**Comment by colinepiloquet** [comment]
> > > @annetill This attribute was first implemented in #2328
> > > In CGMES 3.0 the attribute doesn't exist and in 2.4.15 it doesn't have meaning while it's mandatory.
> > > Proposal is to keep it as `volt` now in order not to change it when regulation is enabled/disabled on RTC.
> > 
> > 
> > Do we manage with your PR to not export this attribute in 3.0?
> 
> No, I’m not sure if this method is shared between 2.4.15 and 3.0.
> 
> I think export of the attributes should be handled in the cgmes 3.0 export of RatioTapChanger.

I tested and the attribute is exported in 3.0.

**Comment by colinepiloquet** [comment]
For not exporting the field when CIM version is 100 it's ok, but I am not sure how to adapt for reimporting

**Comment by nemanja-st** [comment]
> For not exporting the field when CIM version is 100 it's ok, but I am not sure how to adapt for reimporting

@colinepiloquet 
Re-importing is not done anymore because the link to `tculControlMode` was removed in 587c7169d9241c18ec36751c3394d286573a8735.

`RegulatingControl` is now mapped only based on `RegulatingControl` mode.

**Comment by nemanja-st** [comment]
@annetill 
I checked the implementation and it looks ok to me.
I've added a small refactor in check if the attribute needs to be written (it doesn't drag new variable through methods anymore).

**Review by zamarrenolm — APPROVED** [review]

**Pull request merged**
