### PR TITLE
Upgrade2023 notall2

### PR DESCRIPTION
**Pull request by jonenst**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
NO

**What kind of change does this PR introduce?**
Upgrade all the depdencies

**What is the current behavior?**
old runtime deps

**What is the new behavior (if this is a feature change)?**
recent runtime deps

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*
Biggest change is the groovy package migration ?

**Other information**:
see #2702 
Same but rdf4j and univocity are not upgraded

### CODE REVIEW

**Comment by zamarrenolm** [comment]
I've checked that the performance degradation of RDF4J was introduced in 4.3.3.

I've used version 4.3.2 successfully with all CGMES conversion unit tests and with similar performance to the old version we were using (4.2.2).

**Comment by jonenst** [comment]
> I've checked that the performance degradation of RDF4J was introduced in 4.3.3.
good to know. Then probably we'll upgrade to 4.2.2 -> 4.3.2 in this PR, is that what you suggested ?

**Comment by zamarrenolm** [comment]
> > I've checked that the performance degradation of RDF4J was introduced in 4.3.3.
> 
> good to know. Then probably we'll upgrade to 4.2.2 -> 4.3.2 in this PR, is that what you suggested ?

Yes, that is my proposal

**Comment by geofjamg** [comment]
> I've checked that the performance degradation of RDF4J was introduced in 4.3.3.
> 
> I've used version 4.3.2 successfully with all CGMES conversion unit tests and with similar performance to the old version we were using (4.2.2).

We should build a test case showing the performance regression et submit it to RDF4J team

**Pull request merged**
