### PR TITLE
CGMES import. Remove obsolete parameter and methods from config

### PR DESCRIPTION
**Pull request by zamarrenolm**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

Update

**What is the current behavior?**

CGMES import code contains references to parameters that are not used anymore.

**What is the new behavior (if this is a feature change)?**
The code handling the parameter `iidm.import.cgmes.allow-unsupported-tap-changers` have been removed. This parameter is not used in the current conversion from CGMES to IIDM.

Internal parameters containing low impedance threshold in conversion config have also been removed.

The parameter `change-sign-for-shunt-reactive-power-flow-initial-state` has also been removed.

The default value for parameter `create-active-power-control-extension` has been set to `true`.

The documentation has already been updated.

### CODE REVIEW

**Comment by annetill** [comment]
Can we list the parameters that were useful years ago but not now? 
- change-sign-for-shunt-reactive-power-flow-initial-state: why we did that?
- create-active-power-control-extension: default behavior to false is wierd.
-

**Review by So-Fras — APPROVED** [review]

**Comment by zamarrenolm** [comment]
> Can we list the parameters that were useful years ago but not now?
> 
> * change-sign-for-shunt-reactive-power-flow-initial-state: why we did that?
> * create-active-power-control-extension: default behavior to false is wierd.

About change-sign-for-shunt-reactive ... : from the origins of the CGMES converter before it was added to powsybl-core, one of the first examples we considered from test configurations published by ENTSO-E (RealGrid) had the `q` for terminals of shunts with the wrong sign. Other cases in the same data set (MicroGrid, SmallGrid) had it "right", so we established this flag to be able to validate load flow results. This was observed in test configurations from conformity assessment scheme 1.1.3, that is currently deprecated.

About create-active-power-control-extension: when it is `false`, the CGMES normal participation factor (`normalPF`) is still stored as a property of the converted generator.

**Comment by zamarrenolm** [comment]
> > > Can we list the parameters that were useful years ago but not now?
> > > 
> > > * change-sign-for-shunt-reactive-power-flow-initial-state: why we did that?
> > > * create-active-power-control-extension: default behavior to false is wierd.
> > 
> > 
> > About change-sign-for-shunt-reactive ... : from the origins of the CGMES converter before it was added to powsybl-core, one of the first examples we considered from test configurations published by ENTSO-E (RealGrid) had the `q` for terminals of shunts with the wrong sign. Other cases in the same data set (MicroGrid, SmallGrid) had it "right", so we established this flag to be able to validate load flow results. This was observed in test configurations from conformity assessment scheme 1.1.3, that is currently deprecated.
> > About create-active-power-control-extension: when it is `false`, the CGMES normal participation factor (`normalPF`) is still stored as a property of the converted generator.
> 
> change-sign-for-shunt-reactive-power-flow-initial-state: can we remove this parameter then? create-active-power-control-extension: `true` should be new the default behavior.

Yes, the parameter for change sign of shunt reactive power can be removed; all current unit tests will continue to pass.
Agree on creating active power control extension by default.

**Comment by annetill** [comment]
> > > > Can we list the parameters that were useful years ago but not now?
> > > > 
> > > > * change-sign-for-shunt-reactive-power-flow-initial-state: why we did that?
> > > > * create-active-power-control-extension: default behavior to false is wierd.
> > > 
> > > 
> > > About change-sign-for-shunt-reactive ... : from the origins of the CGMES converter before it was added to powsybl-core, one of the first examples we considered from test configurations published by ENTSO-E (RealGrid) had the `q` for terminals of shunts with the wrong sign. Other cases in the same data set (MicroGrid, SmallGrid) had it "right", so we established this flag to be able to validate load flow results. This was observed in test configurations from conformity assessment scheme 1.1.3, that is currently deprecated.
> > > About create-active-power-control-extension: when it is `false`, the CGMES normal participation factor (`normalPF`) is still stored as a property of the converted generator.
> > 
> > 
> > change-sign-for-shunt-reactive-power-flow-initial-state: can we remove this parameter then? create-active-power-control-extension: `true` should be new the default behavior.
> 
> Yes, the parameter for change sign of shunt reactive power can be removed; all current unit tests will continue to pass. Agree on creating active power control extension by default.

Maybe we put `false` by default because we had issues with reference bus vs slack bus. Now we have both extensions.

**Pull request merged**
