### PR TITLE
Allow remote control for SVC during CGMES import + clean up

### PR DESCRIPTION
**Pull request by MioRtia**
Signed-off-by: RALAMBOTIANA MIORA <miora.ralambotiana@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** 
No

**What kind of change does this PR introduce?** 
Feature

**What is the current behavior?**
SVC regulating terminal is always local during CGMES import

**What is the new behavior (if this is a feature change)?**
SVC regulating terminal is as indicated in CGMES files during CGMES import

**Does this PR introduce a breaking change or deprecate an API?** 
No

### CODE REVIEW

**Comment by zamarrenolm** [comment]
> Observed a problem related to regulating terminals linked to busbar sections in node-breaker models.
> 
> If the network is saved (exported to XIIDM) at bus-breaker or bus-branch topology levels, the resulting XIIDM contains a reference to a regulating terminal that is not output in the XIIDM file. Trying to load the generated XIIDM fails because there is a terminal ref for which no actual terminal could be found in the model.
> 
> I will try if the terminal reference exported can be changed to the bus that corresponds to the original busbar section at the topology level that is being exported.

The problem is not specific of the change being made to support remote regulation for SVCs. It can be also reproduced with remote regulation of generators.

**Comment by MioRtia** [comment]
> > Observed a problem related to regulating terminals linked to busbar sections in node-breaker models.
> > If the network is saved (exported to XIIDM) at bus-breaker or bus-branch topology levels, the resulting XIIDM contains a reference to a regulating terminal that is not output in the XIIDM file. Trying to load the generated XIIDM fails because there is a terminal ref for which no actual terminal could be found in the model.
> > I will try if the terminal reference exported can be changed to the bus that corresponds to the original busbar section at the topology level that is being exported.
> 
> The problem is not specific of the change being made to support remote regulation for SVCs. It can be also reproduced with remote regulation of generators.

The regulating terminal is not exported when it is local, is it the case in your test case?
However, it should not fail, there may be an error in the adder, I will look more into it.

**Comment by MioRtia** [comment]
> > Observed a problem related to regulating terminals linked to busbar sections in node-breaker models.
> > If the network is saved (exported to XIIDM) at bus-breaker or bus-branch topology levels, the resulting XIIDM contains a reference to a regulating terminal that is not output in the XIIDM file. Trying to load the generated XIIDM fails because there is a terminal ref for which no actual terminal could be found in the model.
> > I will try if the terminal reference exported can be changed to the bus that corresponds to the original busbar section at the topology level that is being exported.
> 
> The problem is not specific of the change being made to support remote regulation for SVCs. It can be also reproduced with remote regulation of generators.

**Comment by MioRtia** [comment]
> > Observed a problem related to regulating terminals linked to busbar sections in node-breaker models.
> > If the network is saved (exported to XIIDM) at bus-breaker or bus-branch topology levels, the resulting XIIDM contains a reference to a regulating terminal that is not output in the XIIDM file. Trying to load the generated XIIDM fails because there is a terminal ref for which no actual terminal could be found in the model.
> > I will try if the terminal reference exported can be changed to the bus that corresponds to the original busbar section at the topology level that is being exported.
> 
> The problem is not specific of the change being made to support remote regulation for SVCs. It can be also reproduced with remote regulation of generators.

**Comment by MioRtia** [comment]
> > Observed a problem related to regulating terminals linked to busbar sections in node-breaker models.
> > If the network is saved (exported to XIIDM) at bus-breaker or bus-branch topology levels, the resulting XIIDM contains a reference to a regulating terminal that is not output in the XIIDM file. Trying to load the generated XIIDM fails because there is a terminal ref for which no actual terminal could be found in the model.
> > I will try if the terminal reference exported can be changed to the bus that corresponds to the original busbar section at the topology level that is being exported.
> 
> The problem is not specific of the change being made to support remote regulation for SVCs. It can be also reproduced with remote regulation of generators.

Btw isn't this bug linked to the one where regulating terminals are ignored when no topologicalNode are linked to them? In any case, I suggest that if the correction is not trivial, we merge this PR and try and correct the bug in another PR. Could you please send me the test case you used by email?

**Comment by zamarrenolm** [comment]
> > > Observed a problem related to regulating terminals linked to busbar sections in node-breaker models.
> > > If the network is saved (exported to XIIDM) at bus-breaker or bus-branch topology levels, the resulting XIIDM contains a reference to a regulating terminal that is not output in the XIIDM file. Trying to load the generated XIIDM fails because there is a terminal ref for which no actual terminal could be found in the model.
> > > I will try if the terminal reference exported can be changed to the bus that corresponds to the original busbar section at the topology level that is being exported.
> > 
> > 
> > The problem is not specific of the change being made to support remote regulation for SVCs. It can be also reproduced with remote regulation of generators.
> 
> By the way, isn't this bug linked to the one where regulating terminals are ignored when no topologicalNode are linked to them? In any case, I suggest that if the correction is not trivial, we merge this PR and try and correct the bug in another PR. Could you please send me the test case you used by email?

I have provided by email the reference case. I also will try to create a unit tests that reproduce the issue using available public test cases. 

The problem is not related to regulating terminals ignored when no topological nodes are linked. In this case the regulating terminal and control are correctly set in IIDM at node-breaker topology level, and if the case is exported to XML at that level everything is coherent, and the case can be loaded from XIIDM without problems, with the remote regulation correctly expressed. The problem is when the case is saved using a topology level that is NOT node-breaker, then the information put in the XIIDM is not consistent, the regulating terminal refers to an element that do not exist at bus-breaker or bus-view levels.

**Pull request merged**
