### PR TITLE
Remote reactive power control extension

### PR DESCRIPTION
**Pull request by obrix**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

This pull request introduce an extension to handle remote reactive power control. This is work in progress.

**What is the current behavior?** *(You can also link to an open issue here)*

Remote reactive power control is not supported.

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

### CODE REVIEW

**Review by MioRtia — APPROVED** [review]
It is okay for me. The only thing missing is a javadoc for `RemoteReactivePowerControl` to explain what it is.

**Comment by obrix** [comment]
@MioRtia I'll add it, thanks for the review.

**Review by geofjamg — DISMISSED** [review]
Be careful, licences header are missing everywhere

**Review by annetill — APPROVED** [review]

**Review by marqueslanauja — COMMENTED** [review]
Maybe in the method  `setRegulatingControlReactivePower `of the class `RegulatingControlMappingForGenerators` we should consider the `qPercent` and `eqControlEnabled` attributes as in the voltage control (`setRegulatingControlVoltage `method) ?

**Comment by annetill** [comment]
> Maybe in the method `setRegulatingControlReactivePower `of the class `RegulatingControlMappingForGenerators` we should consider the `qPercent` and `eqControlEnabled` attributes as in the voltage control (`setRegulatingControlVoltage `method) ?

It means that for you, for a generator with reactive remote control extension, we will have an other extension to say that that remote reactive control is shared with an other generator? What the `eqControlEnabled` will introduce as change in IIDM modelling?

**Comment by marqueslanauja** [comment]
> > Maybe in the method `setRegulatingControlReactivePower `of the class `RegulatingControlMappingForGenerators` we should consider the `qPercent` and `eqControlEnabled` attributes as in the voltage control (`setRegulatingControlVoltage `method) ?
> 
> It means that for you, for a generator with reactive remote control extension, we will have an other extension to say that that remote reactive control is shared with an other generator? What the `eqControlEnabled` will introduced as change in IIDM modelling?

Since we record the reactive power control in an extension, we can use the same extension to record the  `qPercent` by adding a new field. 
The `eqControlEnabled` is used to determine if the IIDM control is enabled or not. The IIDM control is enabled if the enabled flag at the control and the enabled flag at the equipment are true.

**Comment by MioRtia** [comment]
@marqueslanauja Are the corrections okay for you?

**Review by marqueslanauja — APPROVED** [review]
It is ok.

**Pull request merged**
