### PR TITLE
time-series: TimeSeriesTable, allow to have more than 2gb of data

### PR DESCRIPTION
**Pull request by jonenst**
I still want to test a little more when using MemoryMappedBuffer.

time-series: TimeSeriesTable, allow to have more than 2gb of data

To do this, we use 1 giga (2^30) *bytes* segment into the table. This allows to use
memory mapped buffer for these segments (it would not have been possible if
we had use buffers of 2^30 *elements*) and to use bitshifts and masks to compute indices
(2^30 is the largest power of two no greater than Integer.MAX_VALUE (2^31-1))

Each timeseries is still constrained on its own to have a number of elements that fits in
an array (~2 billions). We keep the previous fillBuffer implementations because they allow to return a
single array without extra copying (and that's up to 16 gb for doubles; unbounded for strings)

We copypaste part of the previous fillBuffer implementation to avoid complicated metaprogramming.
This should also be better for performance.

### CODE REVIEW

**Comment by jonenst** [comment]
sonar caught me on the duplicate code.. I'm going to think harder on how to avoid duplication..

I also started thinking about thread safety. Although I think I didn't change the previous behavior, i'm not sure that this comment "Concurrent load (i.e multi-thread) of data is supported (using same time series list)" is correct because nio buffers are not thread safe. Even if the absolute writes are at different positions, there could be lost data if memory barriers are not used to flush the per core cache lines. Data could maybe even be corrupted because if it's not atomic this could happen inside the individual bytes of our data. For doubles this means false data, but for strings where we use int index this could lead to exceptions. And there may be other racy scenarios.

**Comment by jonenst** [comment]
So array elements are are considered like variables and are not racy for concurrent writes on distinct indices
https://stackoverflow.com/a/6060817/2748664
https://stackoverflow.com/a/8978397/2748664

This person is saying that Buffers behave like arrays..
https://code.i-harness.com/en/q/6ad98e
"Part of my answer is asserting that the a ByteBuffer is no different from a byte[] in terms of data synchronization. I can't find specific documentation that says this, but I suggest that "Thread Safety" section of the java.nio.Buffer doc would mention something about synchronization or volatile if that was applicable. Since the doc doesn't mention this, we should not expect such behavior."

So it should be good. I ran some tests and they were good.

**Comment by jonenst** [comment]
Also, I ran a huge csv test with 12 billions doubles (96 gb) using memory mapped files:
```
[INFO] Running com.powsybl.timeseries.TimeSeriesTableTest
127781 [main] INFO com.powsybl.timeseries.TimeSeriesTable - Allocation of 96 GB for time series table
468105 [main] INFO com.powsybl.timeseries.TimeSeriesTable - 65536 time series (version=1) loaded in 468031 ms
2995611 [main] INFO com.powsybl.timeseries.TimeSeriesTable - Csv written in 2527486 ms

[INFO] Time series API .................................... SUCCESS [50:01 min]
```
it produced a 49G csv file (each double is 3 chars (e.g "1.0") and the separator is one char, so 4 bytes per double instead of 8 in memory. It explains that the size is divided by 2)

Here's the code:
```java

    private void hugeDoubleTester(IntFunction<ByteBuffer> byteBufferAllocator) {
        int lengthm1 = (1 << (20 - 3)) * 3 / 2 - 1;
        TimeSeriesIndex index = new RegularTimeSeriesIndex(0, lengthm1, 1);
        TimeSeriesTable table = new TimeSeriesTable(1, 1, index, byteBufferAllocator);

        List<StoredDoubleTimeSeries> list = new ArrayList<>();
        for (int i = 0; i < 1 << 16; i++) {
            TimeSeriesMetadata metadata = new TimeSeriesMetadata("ts" + i, TimeSeriesDataType.DOUBLE, index); 
            StoredDoubleTimeSeries ts = new StoredDoubleTimeSeries(metadata, new CompressedDoubleDataChunk(0, lengthm1, new double[] {1.0d}, new int[] {lengthm1}));
            list.add(ts);
        }

        table.load(1, list);
        table.writeCsv(Paths.get("/home/harperjon/foo.csv"));
    }

    @Test
    public void hugetestdoublemapped() throws Exception {
        Path path = Paths.get("/path/to/memfile");
        try (FileChannel fileChannel = (FileChannel) Files
                .newByteChannel(path, EnumSet.of(
                        StandardOpenOption.READ,
                        StandardOpenOption.WRITE,
                        StandardOpenOption.TRUNCATE_EXISTING))) {
            AtomicLong counter = new AtomicLong();
            hugeDoubleTester( i -> {
                try {
                    return fileChannel.map(FileChannel.MapMode.READ_WRITE, counter.getAndAdd(i), i);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            });
        }
    }
```

**Comment by jonenst** [comment]
If we merge this, let's consider not squashing the commits because I tried to make them independent of each other. I still have to take care of the sonar issue some way or another

**Comment by geofjamg** [comment]
About the Sonar issue, if it is not possible to fix it (without changing double[] to Double[] which is not acceptable in term of performance), we can just consider it is a Sonar false positive and close the issue.

**Comment by jonenst** [comment]
If we merge this, let's consider not squashing the commits because I made them independent of each other.

**Pull request merged**
