### PR TITLE
Powerfactory: Shunt converter

### PR DESCRIPTION
**Pull request by marqueslanauja**
Signed-off-by: José Antonio Marqués <marquesja@aia.es>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature. Shunt converter code has been reorganized.

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

**Comment by geofjamg** [comment]
Maybe we can try to cover the case where it is defined by rrea and xrea?

**Comment by zamarrenolm** [comment]
> Maybe we can try to cover the case where it is defined by rrea and xrea?

Yes, when the `shtype = 1`, we read the shunt compensator attributes from PF `rrea` and `xrea` in the method `rlShunt`

**Review by zamarrenolm — APPROVED** [review]

**Comment by geofjamg** [comment]
> > Maybe we can try to cover the case where it is defined by rrea and xrea?
> 
> Yes, when the `shtype = 1`, we read the shunt compensator attributes from PF `rrea` and `xrea` in the method `rlShunt`

It seems we use ushnm and qcapn in unit test but not rrea and xrea.

**Comment by zamarrenolm** [comment]
> > > Maybe we can try to cover the case where it is defined by rrea and xrea?
> > 
> > 
> > Yes, when the `shtype = 1`, we read the shunt compensator attributes from PF `rrea` and `xrea` in the method `rlShunt`
> 
> It seems we use ushnm and qcapn in unit test but not rrea and xrea. rrea and xread are equals to zero in test case so not really tested.

Totally right, the lines 80, 81 in `ShuntConverter.java` are not covered by current tests.

**Comment by marqueslanauja** [comment]
> > > > Maybe we can try to cover the case where it is defined by rrea and xrea?
> > > 
> > > 
> > > Yes, when the `shtype = 1`, we read the shunt compensator attributes from PF `rrea` and `xrea` in the method `rlShunt`
> > 
> > 
> > It seems we use ushnm and qcapn in unit test but not rrea and xrea. rrea and xread are equals to zero in test case so not really tested.
> 
> Totally right, the lines 80, 81 in `ShuntConverter.java` are not covered by current tests.

Done. Unitary test added.

**Review by geofjamg — APPROVED** [review]

**Pull request merged**
