### PR TITLE
use -T 2.0C for tests in github actions for speed

### PR DESCRIPTION
**Pull request by jonenst**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
NO

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the current behavior?** *(You can also link to an open issue here)*
tests take 7-9 minutes on github actions workers

**What is the new behavior (if this is a feature change)?**
Hopefully bring it down to 4-5 minutes ?

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*
NO

### CODE REVIEW

**Comment by geofjamg** [comment]
Results are not really convincing, I would close this PR and let it single core.

**Comment by mathbagu** [comment]
@jonenst maybe you should also enable multithreading on sonar step?

**Comment by jonenst** [comment]
If you look into the details, the mac time went from 6min to 3min. So it's promising. But the linux and windows build times didn't go down. I'm looking into it.

(also, the mac build times are consistently faster. Maybe we should do the sonar analysis there ? but we have only 5 workers)

**Comment by jonenst** [comment]
> maybe you should also enable multithreading on sonar step?
It doesn't seem to be supported ? Jul 2018 https://community.sonarsource.com/t/parallel-analysis/1152

**Comment by geofjamg** [comment]
> If you look into the details, the mac time went from 6min to 3min. So it's promising. But the linux and windows build times didn't go down. I'm looking into it.
> 
> (also, the mac build times are consistently faster. Maybe we should do the sonar analysis there ? but we have only 5 workers)

MacOS could be in the future dropped from push build (very few added value in addition to Linux one), so it is clearly not here that we would like to improve performance.

**Comment by jonenst** [comment]
If the mac build is faster and "equivalent" to the linux build, why not use it instead ?

**Comment by mathbagu** [comment]
@jonenst This PR is flagged WIP. Are you working on this? Do we merge it? Do we close it?

**Pull request merged**
