### PR TITLE
Fix cgmes export from scratch

### LINKED ISSUE #2832: Fix issues CGMES export from scratch
### Describe the current behavior

- `TapChangerControl` is not exported when control is disabled.
- `RegulatingControl` is not exported when control is disabled
- `RegulatingControl` is exported when `SynchronousMachine` has no regulation capability, `qMin=qMax` for all `p`
- `RatioTapChanger` exported when there is only one step with `rho=1`
- `tculControlMode` for `RatioTapChanger` set to `reactive` when control is disabled

### Describe the expected behavior

- [ ] Export `TapChangerControl` by default at least for all `PhaseTapChanger`.
- [ ] Export `RegulatingControl` when `SynchronousMachine` has `targetV` and regulation capability, `qMin != qMax` for any `p`
- [ ] Export `RatioTapChanger` when there are multiple steps defined.
- [ ] Set `tculControlMode` to voltage by default.

### Describe the steps

_No response_

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by nemanja-st**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
Fixes #2832 

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

**Comment by colinepiloquet** [comment]
This PR triggers the rule #ControlModeCompatibility of QoCDC. I will check in more details.

**Comment by nemanja-st** [comment]
`neutralStep` cannot be tested because export2cgmes/import2iidm doesn't consider ratio different than 1 to be neutral. In CGMES it's exported correctly, i.e. rho closest to 1 is considered neutral.

**Comment by nemanja-st** [comment]
> This PR triggers the rule #ControlModeCompatibility of QoCDC. I will check in more details.

This is because all PSTs are in current flow regulation mode, only now we're exporting all controls so they get reported.
Before there were no controls on PSTs.

**Comment by annetill** [comment]
I am about to close this PR because we have merged 2 fixes : generator with voltage control capability and neutral step based on smallest rho. About ratio tap changer with just one tap, I think the issue is in our legacy. Remaining issue is `tculControlMode`, right?

**Comment by nemanja-st** [comment]
> I am about to close this PR because we have merged 2 fixes : generator with voltage control capability and neutral step based on smallest rho. About ratio tap changer with just one tap, I think the issue is in our legacy. Remaining issue is `tculControlMode`, right?

That is correct.

By the way, `tculControlMode` doesn't have too much sense because the type of control is described in `TapChangerControl` but it's a mandatory attribute in CGMES 2.4.15.

**Comment by annetill** [comment]
> > I am about to close this PR because we have merged 2 fixes : generator with voltage control capability and neutral step based on smallest rho. About ratio tap changer with just one tap, I think the issue is in our legacy. Remaining issue is `tculControlMode`, right?
> 
> That is correct.
> 
> By the way, `tculControlMode` doesn't have too much sense because the type of control is described in `TapChangerControl` but it's a mandatory attribute in CGMES 2.4.15.

So we have to open a PR with just "String controlMode = "volt";" as fix, right?

**Comment by annetill** [comment]
Finally solved by #2928

**Pull request closed without merging**
