### PR TITLE
Update all pom.xml files to use project.groupId

### PR DESCRIPTION
**Pull request by averycowan**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**
docs update

**What is the current behavior?**
In several cases of the project pom.xml, the parent Group ID is hardcoded, and should be referenced this way instead

**What is the new behavior (if this is a feature change)?**
Internal dependencies using `<groupId>com.powsybl</groupId>` now use `<groupId>${project.groupId}</groupId>`

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

### CODE REVIEW

**Comment by averycowan** [comment]
This is a re-upload of #2780 without using a fork.

**Comment by olperr1** [comment]
Thank you for having re-uploaded your work.

Some module `pom.xml` (such as `iidm/iidm-comparator/pom.xml`) also use hardcoded parent Group Id instead of `${project.groupId}`.
Could you also apply your change to these?

**Comment by averycowan** [comment]
Good idea @olperr1 I made the same edit to all pom.xml files throughout the repo.

**Review by olperr1 — APPROVED** [review]

**Comment by olperr1** [comment]
@averycowan Thank you for your contribution!

**Pull request merged**
