### PR TITLE
[WIP] Correction to main connected component issue for internal nodes without a connected terminal

### PR DESCRIPTION
**Pull request by nicolaslhuillier**
Connected component information has been moved to another class than "NodeTerminal" so that it is also available to nodes that do not have a connected terminal

### CODE REVIEW

**Comment by geofjamg** [comment]
We also have to check performance. A huge number of ConnectedNode will be created (probably millions, > to the number of other objects) so we have to measure cpu, memory and gc performance and compare to previous version.

**Comment by mathbagu** [comment]
ConnectedNode or ConnectivityNode?

**Comment by geofjamg** [comment]
@nicolaslhuillier @mathbagu  we can close this PR replaced by #824?

**Comment by geofjamg** [comment]
Solved by #824

**Pull request closed without merging**
