### PR TITLE
Add GROUND_DISCONNECTOR to existing kinds of Switch

### PR DESCRIPTION
**Pull request by So-Fras**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
#1131
But, in fact, ground disconnectors are not ignored but classified as disconnectors.

**What kind of change does this PR introduce?**
Bug fix

**What is the current behavior?**
No distinction is made between ground disconnectors and disconnectors in IIDM.

**What is the new behavior (if this is a feature change)?**
Ground disconnectors and disconnectors are distinct.
Moreover, no internal connection should be added to the node of the ground disconnector that is connected "to the ground".

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

### CODE REVIEW

**Comment by geofjamg** [comment]
I don't understand why we add a new type of switch. Ground disconnectors are just disconnectors and grounding is related to the way it is connected. Nothing related to a new switch type.

**Review by geofjamg — CHANGES_REQUESTED** [review]
Adding a new type is a weak way to model ground disconnectors. What about if you create a switch with ground disconnector between 2 busbar sections ? Nothing prevent to do it but it does not make any sense. A correct way to model this is to add a new equipment "Ground" that will be connected to the topology and a ground disconnector will just be a disconnector that connect a Ground to the topology.

**Comment by So-Fras** [comment]
Thank you @geofjamg for your remarks, I have added them to the #1131 issue.
@annetill we need to talk about it on your return!

**Comment by annetill** [comment]
In order to enrich the modelling choice, that is directly linked to short-circuit analysis, we have to have in mind our "RTE" modelling but also open data modeling. For example:
Screenshot 2023-11-02 at 15 02 42

**Comment by annetill** [comment]
Rework in #2837

**Pull request closed without merging**
