### PR TITLE
Replace OptionalDouble by Optional

### PR DESCRIPTION
**Pull request by pjeanmarie**
Replace OptionalDouble by Optional to be able to easily replace it by 'null', for instance to use on a constructor which allows null parameters

It will be used for NetworkModification constructor with null parameters like ShuntCompensatorModification.

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

**Comment by pjeanmarie** [comment]
@annetill NB. Following this change powsybl-open-loadflow need also a small fix that I have done, but actual main powsybl-open-loadflow is not compatible with main powsybl-core for other reasons (changes on compare Txt...), is there already a branch on loadflow which use core main? if not do you want me to create it (which name?) (the compare Txt fix seems easy to do so I can do it)?
For now I can work on rao, but maybe at one point I will need the main core and a loadflow branch compatible with main core to properly work on rao new developments.

**Comment by annetill** [comment]
> @annetill NB. Following this change powsybl-open-loadflow need also a small fix that I have done, but actual main powsybl-open-loadflow is not compatible with main powsybl-core for other reasons (changes on compare Txt...), is there already a branch on loadflow which use core main? if not do you want me to create it (which name?) (the compare Txt fix seems easy to do so I can do it)? For now I can work on rao, but maybe at one point I will need the main core and a loadflow branch compatible with main core to properly work on rao new developments.

No integration branch for the moment. Do you need me to do it?

**Comment by pjeanmarie** [comment]
> > @annetill NB. Following this change powsybl-open-loadflow need also a small fix that I have done, but actual main powsybl-open-loadflow is not compatible with main powsybl-core for other reasons (changes on compare Txt...), is there already a branch on loadflow which use core main? if not do you want me to create it (which name?) (the compare Txt fix seems easy to do so I can do it)? For now I can work on rao, but maybe at one point I will need the main core and a loadflow branch compatible with main core to properly work on rao new developments.
> 
> No integration branch for the moment. Do you need me to do it?

Yes it will be usefull for me on open-loadflow and rao, I can do the already needed first changes if it can help

**Comment by olperr1** [comment]
> > > @annetill NB. Following this change powsybl-open-loadflow need also a small fix that I have done, but actual main powsybl-open-loadflow is not compatible with main powsybl-core for other reasons (changes on compare Txt...), is there already a branch on loadflow which use core main? if not do you want me to create it (which name?) (the compare Txt fix seems easy to do so I can do it)? For now I can work on rao, but maybe at one point I will need the main core and a loadflow branch compatible with main core to properly work on rao new developments.
> > 
> > 
> > No integration branch for the moment. Do you need me to do it?
> 
> Yes it will be usefull for me on open-loadflow and rao, I can do the already needed first changes if it can help

Note that the [migration guide for the next release](https://github.com/powsybl/powsybl-core/wiki/Migration-guide-v6.4.0) is already initialized with the instructions regarding the merged PR.

**Comment by olperr1** [comment]
It was decided that we will keep the `OptionalDouble`.
To obtain a `Double` from these methods, the following syntax could be used:
```java
getActivePower().stream().boxed().findFirst().orElse(null)
```

**Pull request closed without merging**
