### PR TITLE
Local computation manager hangs when a java.lang.Error is thrown

### PR DESCRIPTION
**Pull request by geofjamg**
#655

### CODE REVIEW

**Comment by jonenst** [comment]
In the jdk, they use catch(Throwable) to ensure that threads waiting on things don't hang: https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/999dbd4192d0f819cb5224f26e9e7fa75ca6f289/src/java.base/share/classes/java/util/concurrent/CompletableFuture.java

I don't know the completableFuture API and our code yet, but maybe there's a better way to do this where we don't catch ourselves ? like using CompletableFuture::supplyAsync ?

**Comment by geofjamg** [comment]
You can have a look at PR #190 when cancel support has been added. There is kind of flaw in the CompletableFuture design (https://dzone.com/articles/completablefuture-cant-be), cancellation is not propagated to threads which are not interrupted. This is why MyCf has been added.

```java
        MyCf<R> f = new MyCf<>();
        threadPools.execute(() -> {
            f.setThread(Thread.currentThread());
            ...
        });
```
So, I don't think it is possible to use CompletableFuture::supplyAsync.

**Comment by jonenst** [comment]
I think this is equivalent:

```diff
diff --git a/computation-local/src/main/java/com/powsybl/computation/local/LocalComputationManager.java b/computation-local/src/main/java/com/powsybl/computation/local/LocalComputationManager.java
index d4046184..e0ba22b3 100644
--- a/computation-local/src/main/java/com/powsybl/computation/local/LocalComputationManager.java
+++ b/computation-local/src/main/java/com/powsybl/computation/local/LocalComputationManager.java
@@ -315,20 +315,18 @@ public class LocalComputationManager implements ComputationManager {
         Objects.requireNonNull(environment);
         Objects.requireNonNull(handler);
         MyCf<R> f = new MyCf<>();
-        threadPools.execute(() -> {
+        CompletableFuture.supplyAsync(() -> {
             f.setThread(Thread.currentThread());
-            try {
             try (WorkingDirectory workingDir = new WorkingDirectory(config.getLocalDir(), environment.getWorkingDirPrefix(), environment.isDebug())) {
                 f.setWorkingDir(workingDir.toPath());
                 List<CommandExecution> commandExecutionList = handler.before(workingDir.toPath());
                 ExecutionReport report = execute(workingDir.toPath(), commandExecutionList, environment.getVariables(), handler::onExecutionCompletion);
                 R result = handler.after(workingDir.toPath(), report);
-                    f.complete(result);
-                }
-            } catch (Throwable t) {
-                f.completeExceptionally(t);
+                return result;
+            } catch (Exception e) {
+                throw new RuntimeException(e);
             }
-        });
+        }, threadPools).whenComplete((r, e) -> { if (e!=null) { f.completeExceptionally(e); } else { f.complete(r); }});
         return f;
     }
 
```

After discussing this, we decided it's not much more readable than the previous solution because:
  * CompletableFuture.supplyAsync() forbids checked exception so we have to wrap them to RuntimeException (we wouldn't need the catch at all otherwise)
  * Wrapping a CompletableFuture with another CompletableFuture requires the ugly whenCompute call

The version with the call to CompletableFuture.supplyAsync also means that there are more implicit assumptions on the behavior of threads, whereas the other version is explicit since we do everything ourselves.

So let's keep the catch Throwable.

**Comment by jonenst** [comment]
Changed the test a bit so that if we ever have a regression on this, it fails fast instead of hanging the build:
```
$ mvn test
[.. snip..]
[ERROR] hangingIssue(com.powsybl.computation.local.LocalComputationManagerTest)  Time elapsed: 0.113 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.util.concurrent.ExecutionException> but was<java.util.concurrent.TimeoutException>
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] BUILD FAILURE
```

**Pull request merged**
